---
- name: Install virtualenv
  pip: name=virtualenv
  become: yes
  tags:
    - setup

- name: Create the virtualenv
  command: virtualenv {{virtualenv_path}} --no-site-packages
           creates={{virtualenv_path}}/bin/activate
  tags:
    - setup

- name: Install packages inside virtualenv from requirements file
  pip: virtualenv={{virtualenv_path}} requirements={{project_path}}/requirements.txt
  notify:
    - restart uwsgi
    - restart nginx
  tags:
    - setup
    - deploy
