---

# Official PostgreSQL [repository] for debian-based distributions
# [repository]: http://www.postgresql.org/download/


- name: Adding PostgreSQL APT repository key
  become: yes
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags:
    - setup

- name: Add PostgreSQL official APT repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
    state: present
  tags:
    - setup

- name: Install PostgreSQL
  become: yes
  apt:
    name: "postgresql-9.4"
    update_cache: yes
  tags:
    - setup

- name: Create Postgresql user
  when: "'backup' not in group_names"
  become: yes
  become_user: postgres
  vars:
     ansible_ssh_pipelining: true
  postgresql_user: name=sapp password=apj0702
  tags:
    - setup

- name: Creating postgres database
  when: "'backup' not in group_names"
  become: yes
  become_user: postgres
  vars:
     ansible_ssh_pipelining: true
  postgresql_db: name={{project_name}}{{ '1' if project_name == 'sapp-more' else '' }} encoding='UTF-8' owner='sapp'
  tags:
    - setup

- name: comment shared_buffers
  become: yes
  shell: sed -i 's/shared_buffers/#shared_buffers/g' /etc/postgresql/9.4/main/postgresql.conf
  tags:
    - setup

- name: Add parameters for deploy3k in conf file
  become: yes
  shell: "echo {{item}} >> /etc/postgresql/9.4/main/postgresql.conf"
  with_items: deploy3k
  tags:
     - deploy3k

- name: Add parameters for deploy6k in conf file
  become: yes
  shell: "echo {{item}} >> /etc/postgresql/9.4/main/postgresql.conf"
  with_items: deploy6k
  tags:
    - deploy6k
